name: flutter_network
description: Package build upon powerful HTTP client dio.
version: 0.0.1
homepage: https://github.com/mentallyunstable/flutter_network

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.0
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  http_mock_adapter: ^0.4.2

flutter: